apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgCQF4wSpYLULf4q0nxW3EL/0rL5IWLC6UkLv4bjbTxkqSDYFZzmHmQR4QIqUURYzr9312vnhyYVjUAMdqXCTC7G3nZvV3ofjbrFQvvzEdlh/ksUanoMC3eEBLBs2BeYjUcXqSasPTvdgEOLqWffVHDFtp3s4vsHQcNG0lGmFP3eV42Il5YwaGQHEXuEjLxvHZLI3SdfAhmgb+DcncB8HLcwHNRsofKSEhKF56mjpSy17iuQy+Wf+XS//RbSl0y43wdsm468CJi/CVj/BOMeDqGmCtk1CRjM0a4UmVqy+wI1hJv8c4EDwl0mGso0WeEnBkuVjtGJznFEUF0alvuRNiJr0gGShPtPBGW4d49J1G/Ly8DnF4ipYMZ4IuJpE6Xa/ZDpr/50t7CgE/qkD2pxGJexC3LmWMloi5ad7UfKmpaVwNwpRsdzoLwewsiIID/VbP68xS+rEKR5xdlPDfd3PMYeFnLg3dvXFnw1KSi8LcErcdyLrGv3xSmCAmbqTJ/iahLo1Zc8qhMv0QPv6rlZTXKCVwbnw5+bduQMqf3n7xHTWVO3OVJ1tYMVy6aPCD57tmjYAd2mUkOgm00+l1PSR7Gr+1FuoIqFSWXa/eJjP0XCpOMuFPdGCi2drKKp6uPJQqWyMSaCf+p6r4eQNoH8VV41KGIsVyPQ5h3T4pEfhxHlS+jAyMnaiKMf1NFLw24hzYvYJ69g2GcbV7nlA170QveMdocQJLcDx4ZAwNg+S9DVOKKpdLh0pA==
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
