apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/sampleapp

namespace: default

patches:
  - path: ingress.yaml
    target:
      kind: Ingress
      name: caddy-ingress